version: '3.1'

services:
  php:
    container_name: xampp-php7-php
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 81:80
    volumes:
      - C:\Users\otnas\Documents\Dev\categories\php\htdocs\php7:/var/www/html/

  db:
    container_name: xampp-php7-db
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - C:\Users\otnas\Documents\Dev\categories\php\htdocs\php7\mysql-data:/var/lib/mysql

  phpmyadmin:
    container_name: xampp-php7-phpmyadmin
    image: phpmyadmin:5.2.0
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1